

global:
  my_color: "Blue" # "Red"
  is_debug: True # False


ctrl:
  MODE: 'video'  # 'camera'
  DETECT: True
  RECORDING: False
  GUI: False
  ANCHOR: True

  SENDING: True
  RECEIVING: False

  CALIB: False
  SAVE_CSV: False
  SAVE_IMG: False

  CHESSBOARD: False

video:
  bin_video_root: './video'
  bin_video_left: './video/video1/raw_left.mp4'
  bin_video_right: './video/video1/raw_right.mp4'

weights:
  yolov8: 'G:\LangYa\Radar\模型\detect_all\暑假最后\0801_sumup_80.pt'

portx: 'COM7'

car:
  life_span: 20 # 20帧若未刷新则认为不可信

lidar:
  height_threshold: 5.5 # 还没有量，激光雷达如果点比负1.4小，则认为在地面，不要
  min_distance: 1 # 去除距离在这个范围以内的接收点云
  max_distance: 40 # 去除距离在这个范围以外的接收点云
 lidar_topic_name: "/centroid_points" # 点云发布话题名字

communication:
  port: '/dev/ttyUSB0' # 串口
  bps: 115200 # 波特率
  timex: 0.01 # 超时时间

others:
  is_vs_qd: False # 打青岛大学特殊版本
  is_vs_hg: False # 打合肥工业大学特殊版本

area: # 每一个area是一个列表，元素为点的二元组，表示一个凹多边形 , 从左上角逆时针 , 赛场是对称的，红方左下为原点0，0，蓝方右上为28，15
  hero_times_threshold: 2 # 连续5帧检测到英雄才认为英雄在这个区域
  send_double_threshold: 10 # 连续10帧检测到英雄启动双倍易伤
  Blue: # 我方为蓝色时
    length: 2 # 5个区域
    area0:
      - [5.36606, 9.81673]
      - [3.04276, 9.81673]
      - [5.36606, 10.9680]
      - [9.10762, 10.8180]
      - [11.90941, 13.87548]
      - [13.59772, 13.87548]
      - [13.59772, 15.00000]
      - [3.04276, 15.0000]
      - [3.04276, 9.81673] # 红方英雄高地
    area1:
      - [12.53006, 12.84407]
      - [10.168, 9.47071]
      - [10.168, 5.14158]
      - [10.63691, 4.06092]
      - [10.63691, 3.26092]
      - [10.13184, 2.53960]
      - [15.50594, 2.19193]
      - [17.86800, 5.56529]
      - [17.86800, 9.89442]
      - [17.39909, 10.97508]
      - [17.39909, 11.77508]
      - [17.90416, 12.49640] # 中央高地
  Red: # 我方为红色时
    length: 2 # 5个区域
    area0:
      - [ 22.63394, 5.18327 ]
      - [ 24.95724, 5.18327 ]
      - [ 22.63394, 4.0320 ]
      - [ 18.89238, 4.1820 ]
      - [ 16.09059, 1.12452 ]
      - [ 14.40228, 1.12452 ]
      - [ 14.40228, 0.00000 ]
      - [ 24.95724, 0.00000 ]
      - [ 24.95724, 5.18327 ]
    area1:
      - [ 12.53006, 12.84407 ]
      - [ 10.168, 9.47071 ]
      - [ 10.168, 5.14158 ]
      - [ 10.63691, 4.06092 ]
      - [ 10.63691, 3.26092 ]
      - [ 10.13184, 2.53960 ]
      - [ 15.50594, 2.19193 ]
      - [ 17.86800, 5.56529 ]
      - [ 17.86800, 9.89442 ]
      - [ 17.39909, 10.97508 ]
      - [ 17.39909, 11.77508 ]
      - [ 17.90416, 12.49640 ] # 中央高地
