

global:
  my_color: "Blue" # "Red"
  is_debug: True # False


ctrl:
  MODE: 'video'  # 'camera'
  DETECT: True
  RECORDING: False
  GUI: False
  ANCHOR: True

  SENDING: True
  RECEIVING: False

  CALIB: False
  SAVE_CSV: False
  SAVE_IMG: False

  CHESSBOARD: False

video:
  bin_video_root: './video'
  bin_video_left: './video/video1/raw_left.mp4'
  bin_video_right: './video/video1/raw_right.mp4'

weights:
  yolov8: 'G:\LangYa\Radar\模型\detect_all\暑假最后\0801_sumup_80.pt'

portx: 'COM7'

car:
  life_span: 20 # 20帧若未刷新则认为不可信

lidar:
  height_threshold: 5.5 # 还没有量，激光雷达如果点比负1.4小，则认为在地面，不要
  min_distance: 1 # 去除距离在这个范围以内的接收点云
  max_distance: 40 # 去除距离在这个范围以外的接收点云
  lidar_topic_name: "/livox/lidar" # 点云发布话题名字

communication:
  port: '/dev/ttyUSB0' # 串口
  bps: 115200 # 波特率
  timex: 0.01 # 超时时间

others:
  is_vs_qd: False # 打青岛大学特殊版本
  is_vs_hg: False # 打合肥工业大学特殊版本

area: # 每一个area是一个列表，元素为点的二元组，表示一个凹多边形 , 从左上角逆时针 , 赛场是对称的，红方左下为原点0，0，蓝方右上为28，15
  hero_times_threshold: 2 # 连续5帧检测到英雄才认为英雄在这个区域
  send_double_threshold: 10 # 连续10帧检测到英雄启动双倍易伤
  Blue: # 我方为蓝色时
    length: 5 # 5个区域
    area0:
      - [12.05, 15.0]
      - [12.05, 14.30]
      - [13.68, 12.85]
      - [15.02, 14.27]
      - [15.02, 15.0] # 红方英雄下台阶
    area1:
      - [13.68, 12.85]
      - [16.0, 10.0]
      - [18.0, 10.8]
      - [15.02, 14.27] # 红方英雄从台阶到上坡路段
    area2:
      - [16.0, 10.0]
      - [17.6, 8.0]
      - [19.63, 8.66]
      - [18.0, 10.8] # 红方英雄上坡路段
    area3:
      - [17.6, 8.0]
      - [17.6, 6.72]
      - [19.72, 6.01]
      - [19.63, 8.66] # 红方英雄在环高上
    area4:
      - [17.6, 6.72]
      - [15.10, 4.71]
      - [17.82, 3.65]
      - [19.72, 6.01] # 红方英雄在环高下半部分
  Red: # 我方为红色时
    length: 5 # 5个区域
    area0:
      - [13.36, 1.54]
      - [13.36, 0.0]
      - [16.48, 0.0]
      - [16.48, 1.60]
      - [14.96, 2.73] # 蓝方英雄下台阶
    area1:
      - [10.44, 4.91]
      - [13.36, 1.54]
      - [14.96, 2.73]
      - [12.45, 5.73] # 蓝方英雄从台阶到上坡路段
    area2:
      - [8.75, 7.18]
      - [10.44, 4.91]
      - [12.45, 5.73]
      - [10.94, 7.79] # 蓝方英雄上坡路段
    area3:
      - [8.75, 9.71]
      - [8.75, 7.18]
      - [10.94, 7.79]
      - [10.94, 9.04] # 蓝方英雄在环高上
    area4:
      - [10.76, 12.23]
      - [8.75, 9.71]
      - [10.94, 9.04]
      - [12.23, 11.13] # 蓝方英雄在环高下半部分